src/Danvbe/ResmanBundle/Entity/PropertyType.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: admin
 * Date: 08.10.2012
 * Time: 11:16
 * To change this template use File | Settings | File Templates.
 */

namespace Danvbe\ResmanBundle\Entity;


class PropertyType
{

    /**
     * @var string $name the name of the property type
     */
    protected $name;

    /**
     * @var integer $data_type the data_type id
     */
    protected $data_type;

    /**
     * @var ResourceType $resource_type the resource type having this property type
     */
    protected $resource_type;

    /**
     * @var string $type the type of connection (property or identification)
     */
    protected $type;

    /**
     * @return string The name of this property type
     */
    public  function getName(){
        return $this->name;
    }

    /**
     * @param string $name the name to be set
     * @return PropertyType
     */
    public function setName($name){
        $this->name = $name;

        return $this;
    }

    /**
     * @return int the data_type id
     */
    public  function getDataType(){
        return $this->data_type;
    }

    /**
     * @param int $data_type the data_type to be set
     * @return PropertyType
     */
    public function setDataType($data_type){
        $this->data_type = $data_type;

        return $this;
    }

    /**
     * @return ResourceType The resource type of this property type
     */
    public  function getResourceType(){
        return $this->resource_type;
    }

    /**
     * @param ResourceType $resource_type the resource type to be set
     * @return PropertyType
     */
    public function setResourceType($resource_type){
        $this->resource_type = $resource_type;

        return $this;
    }

    /**
     * @return int the type id of the connection
     */
    public  function getType(){
        return $this->type;
    }

    /**
     * @param int $type the type of the connection
     * @return PropertyType
     */
    public function setType($type){
        $this->type = $type;

        return $this;
    }
}

src/Danvbe/ResmanBundle/Resources/views/Admin/base.html.twig
{% extends 'DanvbeResmanBundle::base.html.twig' %}

src/Danvbe/ResmanBundle/Resources/views/Admin/formPropertyType.html.twig
{% extends 'DanvbeResmanBundle:Admin:base.html.twig' %}

{% block body %}
<form action="{{ path('danvbe_resman_admin_property_type_form') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <br />
    <input type="submit" class="button" />
</form>
{% endblock %}

src/Danvbe/ResmanBundle/Resources/views/Admin/formResourceType.html.twig
{% extends 'DanvbeResmanBundle::base.html.twig' %}

{% block body %}
<h3>Formular adaugare tip de resursa</h3>
<form action="{{ path('danvbe_resman_admin_resource_type_form') }}" method="post" {{ form_enctype(form) }}>
    <p>
        {{ form_widget(form) }}
        <br />
        <input class="button" type="submit" value="Salveaza"/>
    </p>
</form>
{% endblock %}

src/Danvbe/ResmanBundle/Resources/views/Admin/listResourceType.html.twig
{% extends 'DanvbeResmanBundle::base.html.twig' %}

{% block body %}
<h2>Lista tipuri de resurse</h2>
<ol>
{% for resource_type in resource_types %}
    <li>
        <a href="{{ path('danvbe_resman_admin_resource_type_show',{'id':resource_type.id}) }}">{{ resource_type.name }}</a>
    </li>
{% endfor %}
</ol>
<p class="post-footer">
    <a href="{{ path('danvbe_resman_admin_resource_type_form') }}" class="readmore">Adauga tip de resursa</a>
</p>
{% endblock %}

src/Danvbe/ResmanBundle/Resources/views/Admin/showResourceType.html.twig
{% extends 'DanvbeResmanBundle::base.html.twig' %}

{% block body %}
<h2>Tip resursa: {{ resource_type.name }}</h2>
<ul>
    <li>
        Identificator:
        {% if (identification) %}
          {% for connected_resource_type in identification.connectedResourceTypes %}
            {{ connected_resource_type.resourceType.name }}
          {% endfor %}
        {% else %}
                <a href="{{ path('danvbe_resman_admin_property_type_form',{'resource_type_id':resource_type.id,'type':'identification'}) }}" class="readmore">Adauga identificator</a>
        {% endif %}
    </li>
</ul>
{% endblock %}

src/Danvbe/ResmanBundle/Resources/views/Admin/test.html.twig
{% extends 'DanvbeResmanBundle:Admin:base.html.twig' %}

{% block body %}
<form action="{{ path('danvbe_resman_administration_test') }}" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
    <input type="submit" />
</form>
{% endblock %}